create table dishes (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  tag text not null check (tag in ('Meat', 'Vegetarian')),
  description text not null default '',
  available boolean not null default true,
  image_path text,
  sort_order int not null default 0
);

create table settings (
  id int primary key check (id = 1),
  price_4 numeric(8,2) not null,
  price_10 numeric(8,2) not null,
  order_fee numeric(8,2) not null,
  max_packs int not null,
  open_day text not null,
  close_day text not null,
  cutoff_time time not null,
  cook_day text not null,
  delivery_days text[] not null,
  delivery_window text not null,
  delivery_area text not null,
  window_override text not null default 'auto' check (window_override in ('auto','open','closed'))
);

create table orders (
  id uuid primary key default gen_random_uuid(),
  ref_num int generated by default as identity (start with 241),
  status text not null default 'pending_payment'
    check (status in ('pending_payment','paid','cancelled','refunded')),
  name text not null,
  email text not null,
  address text not null,
  notes text not null default '',
  delivery_day text not null,
  subtotal numeric(8,2) not null,
  fee numeric(8,2) not null,
  total numeric(8,2) not null,
  stripe_session_id text unique,
  stripe_payment_intent text,
  created_at timestamptz not null default now()
);

create table order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references orders(id) on delete cascade,
  pack_size int not null check (pack_size in (4,10)),
  dish_name text not null,
  qty int not null check (qty > 0),
  unit_price numeric(8,2) not null
);

create table site_content (
  key text primary key,
  value jsonb not null
);

create table inquiries (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null,
  type text not null,
  guests text not null default '',
  message text not null default '',
  created_at timestamptz not null default now()
);

insert into storage.buckets (id, name, public) values ('images', 'images', true);
